### PR TITLE
Feature: Support unit test in go.3

### LINKED ISSUE #117: Feature: Support unit test in go.
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [OpenIMSDK Slack](https://join.slack.com/t/openimsdk/shared_invite/zt-1tmoj26uf-_FDy3dowVHBiGvLk9e5Xkg) and got positive feedback

### Is this feature request related to a problem?

❎ No

### Problem Description

Support go test and get code cover

- https://github.com/agiledragon/gomonkey
- https://blog.csdn.net/xidianhuihui/article/details/131128806

### Solution Description

Add code coverage tool in /server

### Benefits

Enhance system.

### Potential Drawbacks

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by a67793581**
🔍 What type of PR is this?
Enhance system.

Add one of the following kinds:
/kind feature

Optionally add one or more of the following kinds if applicable:
/kind failing-test

👀 What this PR does / why we need it:
My pull request adheres to the code style of this project
My code requires changes to the documentation
I have updated the documentation as required
All the tests have passed
🅰 Which issue(s) this PR fixes:
References #117 
Fix #117 

📝 Special notes for your reviewer:
🎯 Describe how to verify it
https://github.com/a67793581/OpenKF/tree/feat/test/server/test

📑 Additional documentation e.g., RFC, notion, Google docs, usage docs, etc.:
https://github.com/a67793581/OpenKF/tree/feat/test/server/test

### CODE REVIEW

**Review by charles-chenzz — COMMENTED** [review]
I'm not quite sure if we really need to test the config, cus it a wrapper of viper, which already have test in viper package. cc @cubxxw

**Comment by cubxxw** [comment]
> I'm not quite sure if we really need to test the config, cus it a wrapper of viper, which already have test in viper package. cc @cubxxw

Link: https://github.com/openimsdk/openkf/issues/182

**Review by cubxxw — APPROVED** [review]
lgtm cc @IRONICBo

**Comment by a67793581** [comment]
> I'm not quite sure if we really need to test the config, cus it a wrapper of viper, which already have test in viper package. cc @cubxxw

Primarily to ensure as close to 100% test coverage as possible, after all, even the wrapper itself could potentially have issues, although there are currently no known problems.

**Review by IRONICBo — APPROVED** [review]
lgtm

**Pull request merged**
