### PR TITLE
build: Provides Dockerfile deployment of bot modules  

### PR DESCRIPTION
**Pull request by liumingsongning**
<br>

#### 👀 What this PR does / why we need it:

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

#### 🅰 Which issue(s) this PR fixes:

Fixes #

### CODE REVIEW

**Comment by IRONICBo** [comment]
@liumingsongning Please sign up CLA.

**Review by cubxxw — APPROVED** [review]
lgtm

**Comment by cubxxw** [comment]
@liumingsongning It seems that there might be an issue with this CI. Additionally, as this is my first contribution, I kindly request you to review the comments made by the bot and sign the CLA. Thank you for your time and attention.

[OpenKF CI](https://github.com/openimsdk/openkf/actions/workflows/kubekf.yml)

**Comment by cubxxw** [comment]
cc @IRONICBo what do you think?

**Comment by IRONICBo** [comment]
> cc @IRONICBo what do you think?

Maybe  CI  strategy has changed. I will update later.

**Review by IRONICBo — APPROVED** [review]
LGTM Thanks for your contribution :)

**Pull request merged**
